Minor improvements
getmanfred/mac pull request #27
Opened 2023-03-21 15:50 UTC by ignapzs

While taking a look to #24 and #26, I thought this could be some nice minor improvements.
What do you think?

2023-03-22 09:53 UTC, ydarias requested changes
Hello @ignapzs great work again :-)

I left a few comments though since some changes are not working in the intended way.

We really appreciate your work!

2023-03-22 09:53 UTC, ydarias commented on CONTRIBUTING.md
> +- Small Features can be crafted and directly [submitted as a Pull Request](#step-8--create-pull-request).
```suggestion
- Small Features can be crafted and directly [submitted as a Pull Request](#step-8-create-pull-request).
```

2023-03-22 09:53 UTC, ydarias commented on README.md
> +<div style="text-align: center;">
Actually it is not centering the image, while in the original file it is centered :-)

2023-03-22 09:53 UTC, ydarias commented on README.md
> +    <td style="text-align: center;"><a href="https://github.com/jerolba"><img src="https://avatars.githubusercontent.com/u/709055?v=4?s=100" width="100px;" alt="Jerónimo López"/><br /><sub><b>Jerónim
Since it is inside a table the effect could be hard to see, but it could be not affecting the styles in the same way we believe it should do.

2023-03-23 15:02 UTC, ignapzs commented on README.md
> +<div style="text-align: center;">
Yup. My fault, as I thought "Github README viewer" will show it as on IDE or basic HTML. Now I know the trick to center texts in READMEs here :D

2023-03-23 15:03 UTC, ignapzs commented on README.md
> +    <td style="text-align: center;"><a href="https://github.com/jerolba"><img src="https://avatars.githubusercontent.com/u/709055?v=4?s=100" width="100px;" alt="Jerónimo López"/><br /><sub><b>Jerónim
Agree with this. Again, same problem with this CSS properties viewer. Back to original status on last commits

2023-03-23 15:19 UTC, ignapzs commented
Hi @ydarias!
I've just made some new changes and corrections regarding given comments. It also includes a fix for another pending issue.
What do you think about them?

2023-03-27 06:17 UTC, ydarias approved these changes

2023-03-27 06:17 UTC, ydarias commented
I think it is great! :-)

2023-03-27 06:17 UTC, merged